[package]
name = "daf-cache"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
daf-core = { path = "../daf-core" }
async-trait.workspace = true
tokio.workspace = true
thiserror.workspace = true
lru.workspace = true
serde.workspace = true
serde_json.workspace = true
